### PR TITLE
You cannot properly mock class with final method

### PR DESCRIPTION
**Pull request by pilec**
so it cannot be using in unit tests

### CODE REVIEW

**Comment by stekycz** [comment]
:+1:

**Comment by TomasVotruba** [comment]
:+1:

**Comment by pilec** [comment]
Thanks @TomasVotruba , it has been based on my origin/master not upstream/master. But it can be done properly :-).

**Comment by TomasVotruba** [comment]
@pilec I see, gj!

**Comment by enumag** [comment]
:+1: I fixed it in the Identifier trait, but forgot about the IdentifiedEntity class.

The final was there for a reason which is not valid in new versions of Doctrine. See https://github.com/Kdyby/Doctrine/pull/157 for details.

**Comment by fprochazka** [comment]
Thank you :)

**Pull request merged**
