### PR TITLE
getRepository: added serivce for syntax suger in config

### PR DESCRIPTION
**Pull request by Achse**
Because DAO is deprecated

### CODE REVIEW

**Comment by fprochazka** [comment]
I don't think this is good anymore. You should preffer injecting EntityManager and get repositories from it.

**Comment by stekycz** [comment]
I agree however it could be easier and faster to migrate `@doctrine.dao` to `@doctrine.repository` instead of refactoring all code using `EntityDao` to use `EntityManager` which also includes changes in config file.

**Comment by fprochazka** [comment]
You don't actually have to migrade since I'm not going to remove it in foreseeable future.

Better would be to migrade to using the EntityManager or Registry.

**Comment by Achse** [comment]
I agree, it's shitload of work to do, but its the right way to go. :)

**Pull request closed without merging**
