### PR TITLE
Connection: fixed duplicate creation of database platform

### PR DESCRIPTION
**Pull request by matej21**

### CODE REVIEW

**Comment by enumag** [comment]
@matej21 I don't understand, see https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L320-L332.

**Comment by matej21** [comment]
@enumag yes. Problem is that detectDatabasePlatform calls getDatabasePlatformVersion and then connect method. And connect calls detectDatabasePlatform again. In this method new database platform is created. This platform is configured by Kdyby\Doctrine\Connection::connect. But then it returns to the first call of detectPlatform, new platform is created again so it overwrites previous configured platform.

**Comment by enumag** [comment]
@matej21 Shouldn't you fix it in doctrine/dbal then? It doesn't seem to be kdyby-specific bug.

**Comment by matej21** [comment]
@enumag probably, but it is kdyby-related, because kdyby overwrites connect method and configures platform. It was broken by [this](https://github.com/Kdyby/Doctrine/commit/f122242292d5d76928215fde21770758c9b576eb) commit.

**Comment by fprochazka** [comment]
I would argue it was actually fixed by that commit, because without that commit, the Connection couldn't have been lazy again.

**Comment by enumag** [comment]
@matej21 The second call to connect should return immediately because isConnected should be true. Can you look why that isn't true?

**Comment by matej21** [comment]
It probably does return, this is not the issue that connect is called twice. The main issue is that detectDatabasePlatform is called twice. Firstly it is called from the getDatabasePlatform and then it is called from the connect method. Second call creates database platform and kdyby/doctrine registers types on it. Then it returns from connect to the first call of the detectDatabasePlatform. So the original database platform (with registered types) is overwritten.

**Comment by enumag** [comment]
Then the problem applies only when you call getDatabasePlatform before connecting? What about this then?

```php
	/**
	 * @return Doctrine\DBAL\Platforms\AbstractPlatform
	 */
	public function getDatabasePlatform()
	{
		if (!$this->isConnected()) {
			$this->connect();
		}

		return parent::getDatabasePlatform();
	}
```

**Comment by matej21** [comment]
Ok, that looks better :)

**Comment by enumag** [comment]
@matej21 I deleted that previous post because I think it wouldn't actually work.

**Comment by matej21** [comment]
@enumag it actually works great :)

**Comment by enumag** [comment]
@matej21 Still I'm unsure if it's correct solution. ;-)

**Comment by enumag** [comment]
@matej21 Also it would be nice to have a test for this. Master branch of doctrine/dbal is quite different in this case.

**Comment by matej21** [comment]
Test added

**Comment by fprochazka** [comment]
Thank you!

**Pull request merged**
