### PR TITLE
Remove quoteIdentifier from delete

### PR DESCRIPTION
**Pull request by jasin755**
Fixed double quote for delete syntax in PosgreSQL platform

### CODE REVIEW

**Comment by fprochazka** [comment]
And how does it behave now with mysql?

**Comment by jasin755** [comment]
MySQL will be ok, but table names don't escape. I tested PosgreSQL platform in detail. If I have a table name "products" and call the query: 
SELECT * FROM products
 or 
SELECT * FROM Products 
so everything is OK, but if I make table name escape, so there is a problem, for example. 
SELECT * FROM "Products" 
Than appears "Products" does not exist

**Comment by fprochazka** [comment]
And why would you query `Products` if table is named `products`?

**Comment by jasin755** [comment]
I Do Not Know. Name of entity is "Products" and automatically generated table is called "products". If you call $entity_manager-> remove($product); so the SQL is:
DELETE FROM "Products" WHERE "id" =?

**Comment by Majkl578** [comment]
That's because PostgreSQL has case insensitive names by default, but quoted names make it case sensitive.
Likely your DB schema generator (or rather naming strategy) is broken.

**Comment by jasin755** [comment]
I use Doctrine\ORM\Mapping\DefaultNamingStrategy :/

**Comment by fprochazka** [comment]
This is exactly the reason why Doctrine people don't want anything escaped by default.

I think it's better to fix your database to have propper naming.
Or if it's not possible, then be explicit about your schema `@ORM\Entity(table="products")`

**Comment by fprochazka** [comment]
Thank you for your contribution, but this is both incomplete (you haven't removed it from insert and update methods) and it goes against best practices. So I don't it should be merged.

**Comment by jasin755** [comment]
Sorry for incomplete adjustment, If you're willing to do the merge when it will be complete. I will edit it.

**Comment by fprochazka** [comment]
If I remove it, I might broke code that already depends on it. Also I think that you should rather fix your schema to be 1:1 with your entities, than relly on case insensitivity.

**Comment by jasin755** [comment]
There's really not my problem, I create entities and updates the schema. Table names are generated by ourselves. By default, table names in the Doctrine not escape and surely it has a reason. I doubt he just forgot.

**Comment by fprochazka** [comment]
The reason is exactly the problem you've encoutered. The case sensitivity.

**Comment by fprochazka** [comment]
You know what? I would be willing to accept a pullrquest where the Connection class is split in two where one is doing the wiring that Kdyby needs and the other one would extend it and add the escaping. Therefore you would be able to change the class of the service and just use the you want.

**Comment by jasin755** [comment]
So I'm thinking that would be enough to add escape to create tables. I tried

CREATE TABLE Test (
col VARCHAR);

A table created to "test"

CREATE TABLE "Test" (
col VARCHAR);

so it creates a table "Test". This problem would be solved with the fact that I had to manually rename all tables.

**Comment by fprochazka** [comment]
Good rule of thumb is that every column/table name in database is lowercase all the time. Which is why I've changed the [default naming convention in extension a few months ago to underscore](https://github.com/Kdyby/Doctrine/blob/c6b46aea9a8d8f0bfc60c0233c23baf37949e488/src/Kdyby/Doctrine/DI/OrmExtension.php#L58). 

And yes, fixing your schema is still definitely the best option.

**Comment by fprochazka** [comment]
Good rule of thumb is that every column/table name in database is lowercase all the time. Which is why I've changed the [default naming convention in extension a few months ago to underscore](https://github.com/Kdyby/Doctrine/blob/c6b46aea9a8d8f0bfc60c0233c23baf37949e488/src/Kdyby/Doctrine/DI/OrmExtension.php#L58). It should auto generate `article_comment` from entity `ArticleComment`.

You can tell the schema the table name explicitly, in which case the naming convention doesn't matter

```php
/**
 * @ORM\Entity()
 * @ORM\Table(name="product_actions")
 */
class ProductAction extends Identified
{
```

this way, the doctrine will always use the table name you've provided and it shouldn't be required to change your schema. But I still think that fixing your schema is definitely the best option.

**Pull request closed without merging**
