### PR TITLE
Added line number to tracy panel

### PR DESCRIPTION
**Pull request by paveltizek**
This add line to tracy panel, where SQL was executed.

### CODE REVIEW

**Comment by enumag** [comment]
It would be better to send this PR to the 3.3 branch. At this point it is unsure if there will ever be a release from the master branch since nobody is working on it.

**Comment by paveltizek** [comment]
OK, I will send new PR to 3.3 branch. I was thinking that master is actual branch because is newer.

**Comment by enumag** [comment]
I merged current 3.3 branch to master just in case someone wanted to work on it. There were many conflicts which would be difficult to fix later.

**Comment by paveltizek** [comment]
So what should I do? Fetch, update v3.3 and send new PR or let it be?

**Comment by enumag** [comment]
Update v3.3.

**Comment by paveltizek** [comment]
Thanks. I have another non related question, is posible to show base file where SQL query commes? 

What I mean: for example I have some presenter, which call some manager, so Tracy show me 'SomeManager.php line 100' but I need to show 'SomePresenter.php line 50'. Is it even posible? In NDBT is little trick with `Debugger::getBlueScreen()->collapsePaths = [paths]`. Is there something similar what I cant find?

**Comment by enumag** [comment]
I don't think so. I faintly remember trying to hack it once in the past but without much success. If I remember correctly there is a mechanism somewhere to not show the paths form doctrine classes but it's not configurable to add other paths.

**Pull request closed without merging**
