### PR TITLE
Drop geometry types support

### PR DESCRIPTION
**Pull request by foxycode**
Related to #238

### CODE REVIEW

**Comment by fprochazka** [comment]
If anyone was using these, I encourage you to copy the code (or write better) and create your own package, because they will be removed in `v4.0`.

**Comment by fprochazka** [comment]
@foxycode thank you

**Comment by fprochazka** [comment]
FYI, this looks really good on first look: https://github.com/creof/doctrine2-spatial

**Comment by foxycode** [comment]
@fprochazka What about that enum type? Shouldn't we drop it too? There sure are independent packages with doctrine types, I use `oro/doctrine-extensions` which doesn't have enum, but we can surely create independent type package too.

**Comment by fprochazka** [comment]
@foxycode agreed, but I don't like the current implementation. Also, using enums with mysql is pure shit, and using one enum with postgres doesn't make sense.

So it probably makes sense to drop the enum too.

**Pull request merged**
