### PR TITLE
Final methods can't be mocked

### PR DESCRIPTION
**Pull request by Grez**

### CODE REVIEW

**Comment by enumag** [comment]
We know. Unfortunately these have to be final for performance reasons because of a bug in Doctrine/ORM.

**Comment by enumag** [comment]
See https://github.com/Kdyby/Doctrine/pull/157 and https://github.com/doctrine/common/pull/356

**Comment by enumag** [comment]
@Grez If you want this fixed you will have to send a PR to Doctrine/ORM. It won't be easy though. I can give you a few tips about what needs to be changed if you want.

**Comment by fprochazka** [comment]
@Grez you can always just copy the trait and modify it to your needs :) But for reasons mentioned by @enumag, I cannot merge this.

**Pull request closed without merging**
