### PR TITLE
Drop ENUM type

### PR DESCRIPTION
**Pull request by foxycode**
Related to #250

I was thinking about completely remove method `setDbalTypes` and stuff from `Connection`. Did you implemented it just for types from `Kdyby` package or will removing brake adding custom types using config?

### CODE REVIEW

**Comment by fprochazka** [comment]
> I was thinking about completely remove method setDbalTypes and stuff from Connection.

The official bundle from doctrine solves it using [ConnectionFactory](https://github.com/doctrine/DoctrineBundle/blob/1c50bb90a702447def929a185e468096fe205953/ConnectionFactory.php) which in fact breaks lazy connection, since databaseplatform is dependent on database version and is created only after doctrine connects to the db (= touching db platform forces connection).

We could try to push this feature to doctrine dbal, so the bundle can use it too. I wouldn't wanna just remove it though.

**Comment by fprochazka** [comment]
@foxycode  Also, I'm not sure why, but the tests have failed.

**Comment by foxycode** [comment]
@fprochazka Fixed and passing.

**Comment by foxycode** [comment]
@fprochazka Hope now it's ok.

**Comment by fprochazka** [comment]
@foxycode great work :+1:

**Comment by fprochazka** [comment]
Thank you :)

**Pull request merged**
