### PR TITLE
Converted arrays to short syntax

### PR DESCRIPTION
**Pull request by foxycode**
Since doctrine/orm already supports php >=5.4, there is no need to keep old array syntax.

### CODE REVIEW

**Comment by enumag** [comment]
Confirmed. Doctrine/ORM 2.5 (required by master Kdyby/Doctrine) indeed requires PHP >=5.4. Good to merge (although commits like this are very bad for git blame).

**Comment by foxycode** [comment]
@enumag You are right, but this repo already have mixed long and short array syntax and it makes me furious when I want to create pull.

**Comment by enumag** [comment]
@foxycode Me too. Welcome to the club. :-)

**Comment by fprochazka** [comment]
I wanned to keep the compatibility with 5.3 as long as possible, but since doctrine/orm dropped it, there is no point in it anymore :)

**Comment by fprochazka** [comment]
@foxycode can you please also add [to .travis.yml](https://github.com/Kdyby/Doctrine/blob/master/.travis.yml#L34) the `--short-arrays` option, which [code-checker](https://github.com/nette/code-checker#code-checker) supports?

**Comment by foxycode** [comment]
@fprochazka Done. I also added `"php": ">=5.4"` to composer.json. Hope it's ok.

Please, tell me. Why is php7 is allowed failures? I'd like to change that.
Why you downloading own composer in travis? What is different in it?

**Comment by TomasVotruba** [comment]
:+1: Looks great!

**Comment by fprochazka** [comment]
Thank you!

> Please, tell me. Why is php7 in allowed failures? I'd like to change that.

Nobody just got to changing it since PHP7 stabilized :)

> Why you downloading own composer in travis? What is different in it?

what do you mean?

**Comment by fprochazka** [comment]
@foxycode https://github.com/Kdyby/Doctrine/commit/33d1bc3b29bebaf91a54b4a101c908f36a682761 :)

**Comment by TomasVotruba** [comment]
@foxycode Probably these lines: https://github.com/Kdyby/Doctrine/blob/33d1bc3b29bebaf91a54b4a101c908f36a682761/.travis.yml#L25-L26

**Comment by foxycode** [comment]
@fprochazka Thanks for php7 :) I already using it in production with Doctrine.

> Why you downloading own composer in travis? What is different in it?
As @TomasVotruba said. I'd like to know for what is composer-nette from TesterExtras good for.

**Comment by fprochazka** [comment]
@foxycode it fixes nette dependencies for different versions of nette

**Pull request merged**
