### PR TITLE
PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by xificurk**
Getting rid of `Nette\Object` that cannot be used in PHP 7.2

### CODE REVIEW

**Comment by xificurk** [comment]
The build against dev dependencies passes, but at the moment there are no stable versions of kdyby/doctrine-cache, kdyby/events, kdyby/console and kdyby/annotations compatible with PHP 7.2.

**Comment by enumag** [comment]
@xificurk Could you rebase this to the 3.2 branch?

**Comment by xificurk** [comment]
@enumag rebased, but for some reason travis build was not triggered. Could you look into it?

**Comment by enumag** [comment]
@xificurk I have no idea why. I think I'll just merge this and we'll see potential failures on the 3.2 branch then.

Thank you!

**Comment by JanGalek** [comment]
I tested change Nette\Object to trait SmartObject for current stables version of Kdyby packages, and everything looks ok :)

**Comment by enumag** [comment]
@JanGalek Yeah, Object issues are indeed solved. There are some other problems though - Doctrine 2.6 and RobotLoader 3.0.

**Comment by JanGalek** [comment]
@enumag ou, Can I help ? :)

**Comment by enumag** [comment]
@JanGalek Sure you can. :)

For RobotLoader there is a PR https://github.com/Kdyby/Doctrine/pull/304 but it is not in a mergeable state. And it would be better if someone could figure out why is RobotLoader even used in the first place - ideally I'd like to drop it.

For Doctrine 2.6 try to install the 3.2 branch of kdyby/doctrine along with doctrine/orm 2.6 and test your app for any issues.

**Comment by JanGalek** [comment]
@enumag thanks, I was looking for RobotLoader now, I will continue morning, I will try it ;)

**Pull request merged**
