### PR TITLE
nette 2.4 Nette\DI\Statement::setEntity deprecated fix

### PR DESCRIPTION
**Pull request by paveljanda**

### CODE REVIEW

**Comment by fprochazka** [comment]
Thanks for the PR, but I'm gonna wait till DG stops making BC Breaks (at least for a few days) and then look into it. Right now, the nette/di+nette/bootstrap is completely broken.

**Comment by paveljanda** [comment]
Agreed.

**Comment by dg** [comment]
This should be merged

**Comment by fprochazka** [comment]
@paveljanda thank you!

**Comment by hantc** [comment]
Pls, how to get dev version of doctrine with this fixed (/merged) issue? thanks in advance

**Comment by fprochazka** [comment]
@hantc add `"kdyby/doctrine": "dev-master"` to your `composer.json`, but be aware that there are BC Breaks in the master, and more are comming.

**Pull request merged**
