### PR TITLE
Remove LIMIT 1 for fetchOne

### PR DESCRIPTION
**Pull request by jasin755**
setMaxResult(1) limits oneToMany/manyToMany associations.

### CODE REVIEW

**Comment by fprochazka** [comment]
I'm not entirely sure about this... I know this criples toMany relations, but shouldn't it be a bit smarter? This might be a BC Break for some people. Better would be to use the doctrine paginator tool to fetch only first row.

**Comment by enumag** [comment]
Which makes this a duplicate of #118.

**Comment by fprochazka** [comment]
Not really, since this is trying to solve it.

**Comment by jasin755** [comment]
In my opinion, fetchOne would be equivalent to getOneOrNullResult.

**Comment by fprochazka** [comment]
@jasin755 I agree. But the problem is, what will it do, when I **only** remove the `setMaxResults(1)` and then run a query that returns more than one result? It throws. Which is a BC break.

Now that I think about it, I've opened `3.0-dev`, so I might actually break it a bit.

**Comment by jasin755** [comment]
I would not see a problem in the exception. If used fetchOne and return to more rows the comrade made a mistake somewhere and can help him to reveal it (eg. by adding limit to query object)

**Comment by jasin755** [comment]
Are you going to merge with 3.0@dev ?

**Comment by fprochazka** [comment]
I probably will.

**Comment by matej21** [comment]
yep, it is a bc break :\

Any idea how to setup maxResults? I cannot override fetchOne because getQuery is private..

**Comment by fprochazka** [comment]
@matej21 what is your use case? do you wanna fetch one specific row, or just the first row from some result?

**Comment by matej21** [comment]
@fprochazka I wanna fetch first row from the result

**Comment by fprochazka** [comment]
It was stupid of me to merge this in a hurry. I'm reverting this https://github.com/Kdyby/Doctrine/commit/022976d52107c417d030537b591e3013893ba9d9 and will tag `v3.0.1` with the revert as a fix of the BC.
I'm also adding a new commit https://github.com/Kdyby/Doctrine/commit/ed3ea61b8e30821452e22516422b65ff3bb2d446 that allows overriding the `fetchOne`, so you can change the behaviour if you know what you're doing.

**Pull request merged**
